Vagrant.configure("2") do |config|
  config.vm.box = "base"
  #config.vm.network "private_network", type: "static", ip: "192.168.33.10" # Set your desired static IP
  config.vm.define "frontend" do |frontend|
    frontend.vm.box =  "generic/ubuntu2204"
    frontend.vm.network "public_network" #Bridged Network
    config.vm.network "forwarded_port", guest: 3000, host: 8080, host_ip: "10.0.2.15"
    config.vm.synced_folder ".", "/var/www/"
    config.ssh.username = "vagrant"
    config.ssh.password = "vagrant"
    #Provisioning script for frontend
    config.vm.provision "shell", inline: <<-SHELL
      sudo nano /etc/systemd/system/my-react-app.service
      curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
      sudo apt-get install -y nodejs
      sudo rm -rf Demo_Application
      git clone -b Frontend-Updated https://github.com/saikirangouli/Demo_Application.git 
      sudo git checkout Frontend-Updated
      cd Demo_Application/
      npm install
      npm install axios
      npm run build
      cat << EOF | sudo tee /etc/systemd/system/react-app.service
      [Unit]
      Description=React Application
      [Service]
      WorkingDirectory=/home/vagrant/Demo_Application
      ExecStart=/usr/bin/npm start
      Restart=always
      User=vagrant
      Group=vagrant
      Environment=PATH=/usr/bin:/usr/local/bin
      Environment=NODE_ENV=production
      [Install]
      WantedBy=multi-user.target
      EOF
      sudo systemctl daemon-reload
      sudo systemctl enable react-app
      sudo systemctl start react-app

      #npm start
    SHELL
  end
end 
#frontend ---> 192.168.0.101
#path --> /home/vagrant/Demo_Application