Vagrant.configure("2") do |config|
  config.vm.box = "base"
  # Frontend VM Setup
  config.vm.define "backend" do |backend|
    backend.vm.box =  "generic/ubuntu2204"
    backend.vm.network "public_network" #Bridged Network
    config.vm.network "forwarded_port", guest: 3000, host: 8000, host_ip: "10.0.2.15"
    config.vm.synced_folder ".", "/var/www/" #instaed f . give host machine path of req folder path
    config.ssh.username = "vagrant"
    config.ssh.password = "vagrant"
    #Provisioning script for frontend
    config.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      sudo apt install -y python3 python3-pip
      pip3 install django
      pip3 install djangorestframework
      pip3 install django-cors-headers
      pip3 install psycopg2-binary
      git clone https://github.com/saikirangouli/Demo_Application.git
      sudo git checkout Backend
      git fetch
      cd Demo_Application/
      git pull origin Backend
      python3 manage.py makemigrations
      python3 manage.py migrate
      cat << EOF | sudo tee /etc/systemd/system/django-app.service
      [Unit]
      Description=Your Django Application
      After=network.target

      [Service]
      User=vagrant
      Group=vagrant
      WorkingDirectory=/home/vagrant/Demo_Application
      ExecStart=/usr/bin/python3 manage.py runserver 0.0.0.0:8000

      [Install]
      WantedBy=multi-user.target
      EOF


      sudo systemctl daemon-reload
      sudo systemctl enable django-app
      sudo systemctl start django-app

    SHELL
  end
end 
