Vagrant.configure("2") do |config|
  config.vm.box = "alvistack/ubuntu-22.04"
  config.vm.hostname = "frontend"
  config.vm.network "private_network", type: "static", ip: "192.168.33.12"
  config.vm.network "forwarded_port", guest: 3000, host: 8000, host_ip: "127.0.0.1"
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.vm.provision "shell", inline: <<-SHELL
    sudo nano /etc/systemd/system/my-react-app.service
    curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
    sudo apt-get install -y nodejs
    sudo rm -rf Demo_Application
    git clone -b Frontend-Updated https://github.com/saikirangouli/Demo_Application.git 
    sudo git checkout Frontend-Updated
    cd Demo_Application/
    npm install

  SHELL
  config.vm.provision "shell", path: "./frontend_script.sh"
   
    #npm start

end
