Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"  # You can choose a different box
  config.vm.network "public_network"

  # Provisioning script to install PostgreSQL and create user and database
  config.vm.provision "shell", inline: <<-SHELL
    # Update package list and install PostgreSQL
    sudo apt-get update
    sudo apt-get install -y postgresql postgresql-contrib
    # Start PostgreSQL service
    #sudo service postgresql start
    sudo systemctl start postgresql #new line
    sudo systemctl enable postgresql #new line 
    echo "listen_addresses = '*'" | sudo tee -a /etc/postgresql/$(ls /etc/postgresql/)/main/postgresql.conf
    echo "host all all 0.0.0.0/0 trust" | sudo tee -a /etc/postgresql/$(ls /etc/postgresql/)/main/pg_hba.conf
    # Drop the database using psql
    sudo -u postgres psql -c "DROP DATABASE IF EXISTS my_database;"
    # Drop the role using psql
    sudo -u postgres psql -c "DROP ROLE IF EXISTS my_user;"
    sudo -u postgres psql -c "CREATE USER my_user WITH PASSWORD 'my_password';"
    sudo -u postgres createdb -O my_user my_database
  SHELL
end

#sudo -u postgres psql

#updated 
#fronted --> 192.168.0.101
#backend --> 1 192.168.0.109
#database --> 192.168.0.106/24