Vagrant.configure("2") do |config|
  config.vm.box = "alvistack/ubuntu-22.04"
  config.vm.hostname = "backend"
  config.vm.network "private_network", type: "static", ip: "192.168.33.11"
  config.vm.network "forwarded_port", guest: 8000, host: 3333, host_ip: "127.0.0.1"
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt install -y python3 python3-pip
    pip3 install django
    pip3 install djangorestframework
    pip3 install django-cors-headers
    pip3 install psycopg2-binary
    git clone -b Backend https://github.com/saikirangouli/Demo_Application.git 
    sudo git checkout Backend
    cd Demo_Application/
    python3 manage.py makemigrations
    python3 manage.py migrate

  SHELL
  config.vm.provision "shell", path: "./backend_script.sh"
   
    #npm start

end
