Vagrant.configure("2") do |config|
  config.vm.box = "alvistack/ubuntu-22.04"
  config.vm.hostname = "database"
  config.vm.network "private_network", type: "static", ip: "192.168.33.10"
  config.vm.network "forwarded_port", guest: 5432, host: 5000, host_ip: "127.0.0.1"
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y postgresql postgresql-contrib
    sudo systemctl start postgresql #new line
    sudo systemctl enable postgresql #new line 
    echo "listen_addresses = '*'" | sudo tee -a /etc/postgresql/$(ls /etc/postgresql/)/main/postgresql.conf
    echo "host all all 0.0.0.0/0 trust" | sudo tee -a /etc/postgresql/$(ls /etc/postgresql/)/main/pg_hba.conf
    #echo "host all all 192.168.33.11/32 md5" >> ""/etc/postgresql/$(ls /etc/postgresql/)/main/pg_hba.conf""
    # Drop the database using psql
    sudo -u postgres psql -c "DROP DATABASE IF EXISTS my_database;"
    #Drop the role using psql
    sudo -u postgres psql -c "DROP ROLE IF EXISTS my_user;"
    sudo -u postgres psql -c "CREATE USER my_user WITH PASSWORD 'my_password';"
    sudo -u postgres createdb -O my_user my_database
    sudo systemctl restart postgresql

  SHELL
  #config.vm.provision "shell", path: "./port_rule.sh"

end 