Vagrant.configure("2") do |config|
  # Use an Ubuntu 22.04 LTS box
  config.vm.box = "ubuntu/focal64"
  config.vm.network "public_network"
  config.vm.network "forwarded_port", guest: 6379, host: 8080, host_ip: "10.0.2.15"
  # Update the system and install Redis
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install redis-server -y
  SHELL
end
#192.168.0.102
# sudo nano /etc/redis/redis.conf
#sudo systemctl restart redis-server
